### ISSUE TITLE
Provide Test Input/Output files for the tool

### ISSUE THREAD

**Issue by k3yavi** [COMBINE-lab/CSE549-txpCoverage#8]

**Comment by k3yavi** [comment]
hey @aksinghal5590 can you please also upload the interim files `*.pos`, `*.sf` and output file `*.csv` as an example inside `test_data` folder too. Thanks!

**Comment by aksinghal5590** [comment]
Added newTestData.tar.gz

**Comment by k3yavi** [comment]
lovely!
